version: "3.2"
services:
    mariadb:
        image: mariadb
        container_name: db
        ports:
          - "3696:3306"
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: db
          MYSQL_USER: root
          MYSQL_PASSWORD: root
        volumes:
          - ./docker/db:/var/lib/mysql
        restart: always
        networks:
          - network_n1
          - network_nginx_proxy
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
          - PMA_ARBITRARY=1
          - PMA_HOST=db
          - PMA_USER=root
          - PMA_PASSWORD=root
          - MYSQL_DATABASE=jsc
        links:
          - mariadb
        networks:
          - network_n1
          - network_nginx_proxy
        ports:
          - 4040:80
        volumes:
          - ./docker-config/phpmyadmin/sessions:/sessions
          - ./phpmyadmin/sessions:/sessions
          - ./phpmyadmin/phpmyadmin-misc.ini:/usr/local/etc/php/conf.d/phpmyadmin-misc.ini
networks:
    network_nginx_proxy:
        external: 
            name: nginx-proxy
    network_n1:
        external: 
            name: dbshared